### ISSUE TITLE
Question: Format url

### ISSUE THREAD

**Issue by SinonCute** [yumetodo/google-photos-album-image-url-fetch#25]
I see now we have 2 different format URLs, but now we can only get the path **/pw** and the path format without **/pw** now there is no way to get it but since I see someone just using the format without **/pw** to get images and upload new images daily, is there still a way to get it?

**Comment by yumetodo** [comment]
related: #19, #23

**Comment by SinonCute** [comment]
So they switched to new format and dropped the old one, we no longer can get the old format?

**Comment by yumetodo** [comment]
I don't know what Google thinks about it. Currently, these 3 formats can be observed with solid deviation.

**Comment by yumetodo** [comment]
Now I have released v3.2.0 which supports the change mentioned in #23.

If you have more question about this library, please reopen this issue or create another issue!
