### ISSUE TITLE
Throwing 403 status code while accessing public google photos link

### ISSUE THREAD

**Issue by sadashiv-sumasoft** [yumetodo/google-photos-album-image-url-fetch#26]
Hello,

I have integrated your pacakge at one sandbox for testing.
But It is throwing the 403 response code for every single google photos link

Could you please check what is the issue?
FYI even with axios it is throwing same status code.

![Screenshot (547)](https://github.com/yumetodo/google-photos-album-image-url-fetch/assets/89510166/9bc2cbf9-1ea9-4a62-9cd4-8a78a60e7e28)

**Comment by yumetodo** [comment]
Now I closed this issue because I cannot reproduce the error.
